namespace: naif_saleh
name: infra_tools
version: 1.0.0
authors:
  - Naif Saleh Alsebaeai
description: Unified Ansible collection containing docker_setup and laravel_deploy roles
readme: README.md
license: MIT
tags:
  - devops
  - docker
  - laravel
